apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetport: 8000

  type: ClusterIp    
